export interface GolfCourse {
  site_name: string;
  town: string;
  easting: number;
  northing: number;
  facility_sub_type: string;
}

export const golfCourses: GolfCourse[] = [
  { site_name: "Aberdeen Ladies' Golf Club", town: "Aberdeen", easting: 394939, northing: 809924, facility_sub_type: "Golf Course" },
  { site_name: "Auchmill Golf Course", town: "ABERDEEN", easting: 389600, northing: 808900, facility_sub_type: "Golf Course" },
  { site_name: "Balnagask Golf Course", town: "Aberdeen", easting: 395925, northing: 805162, facility_sub_type: "Golf Course" },
  { site_name: "Craibstone Golf Centre", town: "Aberdeen", easting: 386445, northing: 810328, facility_sub_type: "Golf Course" },
  { site_name: "Deeside Golf Club", town: "NR ABERDEEN", easting: 388400, northing: 802200, facility_sub_type: "Golf Course" },
  { site_name: "Hazelhead Golf Course", town: "NR ABERDEEN", easting: 389200, northing: 805500, facility_sub_type: "Golf Course" },
  { site_name: "Kings Links Golf Centre", town: "ABERDEEN", easting: 394900, northing: 807500, facility_sub_type: "Golf Course" },
  { site_name: "Kippie Lodge Sports & Country Club", town: "NR ABERDEEN", easting: 384781, northing: 801439, facility_sub_type: "Golf Course" },
  { site_name: "Murcar Golf Club", town: "NR ABERDEEN", easting: 395700, northing: 812200, facility_sub_type: "Golf Course" },
  { site_name: "Nigg Bay Golf Course", town: "ABERDEEN", easting: 396000, northing: 805400, facility_sub_type: "Golf Course" },
  { site_name: "Peterculter Golf Club", town: "NR ABERDEEN", easting: 383700, northing: 799500, facility_sub_type: "Golf Course" },
  { site_name: "Royal Aberdeen Golf Club", town: "NR ABERDEEN", easting: 395000, northing: 809800, facility_sub_type: "Golf Course" },
  { site_name: "Aboyne Golf Club", town: "ABOYNE", easting: 353400, northing: 799400, facility_sub_type: "Golf Course" },
  { site_name: "Alford Golf Club", town: "ALFORD", easting: 357800, northing: 816300, facility_sub_type: "Golf Course" },
  { site_name: "Aspire Golf Centre", town: "NR ABERDEEN", easting: 389816, northing: 802276, facility_sub_type: "Golf Course" },
  { site_name: "Auchenblae Golf Club", town: "LAURENCEKIRK", easting: 373100, northing: 779100, facility_sub_type: "Golf Course" },
  { site_name: "Ballater Golf Club", town: "BALLATER", easting: 336700, northing: 795400, facility_sub_type: "Golf Course" },
  { site_name: "Ballindalloch Castle Golf Course", town: "NR ABERLOUR", easting: 317898, northing: 835789, facility_sub_type: "Golf Course" },
  { site_name: "Balmoral Golf Course", town: "NR BALLATER", easting: 326300, northing: 794500, facility_sub_type: "Golf Course" },
  { site_name: "Banchory Golf Club", town: "Banchory", easting: 369188, northing: 795563, facility_sub_type: "Golf Course" },
  { site_name: "Berryhill Driving Range", town: "NR PETERHEAD", easting: 409708, northing: 846401, facility_sub_type: "Golf Driving Range" },
  { site_name: "Braemar Golf Club", town: "BRAEMAR", easting: 314900, northing: 790300, facility_sub_type: "Golf Course" },
  { site_name: "Cheyne Hill Golf Club", town: "STONEHAVEN", easting: 383500, northing: 787400, facility_sub_type: "Golf Course" },
  { site_name: "Cruden Bay Golf Club", town: "CRUDEN BAY", easting: 408200, northing: 835900, facility_sub_type: "Golf Course" },
  { site_name: "Duff House Royal Golf Club", town: "BANFF", easting: 369000, northing: 863600, facility_sub_type: "Golf Course" },
  { site_name: "Dunecht House Golf Club", town: "ECHT", easting: 375400, northing: 807700, facility_sub_type: "Golf Course" },
  { site_name: "Fraserburgh Golf Club", town: "FRASERBURGH", easting: 400561, northing: 865307, facility_sub_type: "Golf Course" },
  { site_name: "Fyvie Golf Club", town: "Turriff", easting: 376644, northing: 837760, facility_sub_type: "Golf Course" },
  { site_name: "Huntly Golf Club", town: "Huntly", easting: 353096, northing: 840417, facility_sub_type: "Golf Course" },
  { site_name: "Inchmarlo Golf Centre", town: "BANCHORY", easting: 368054, northing: 796614, facility_sub_type: "Golf Course" },
  { site_name: "Insch Golf Club", town: "INSCH", easting: 362500, northing: 828500, facility_sub_type: "Golf Course" },
  { site_name: "Inverallochy Golf Club", town: "FRASERBURGH", easting: 404600, northing: 864700, facility_sub_type: "Golf Course" },
  { site_name: "Kemnay Golf Club", town: "KEMNAY", easting: 372900, northing: 815600, facility_sub_type: "Golf Course" },
  { site_name: "Kintore Golf Club", town: "KINTORE", easting: 380000, northing: 816700, facility_sub_type: "Golf Course" },
  { site_name: "Longside Golf Club", town: "LONGSIDE", easting: 403300, northing: 847700, facility_sub_type: "Golf Course" },
  { site_name: "Lumphanan Golf Club", town: "NR TORPHINS", easting: 358800, northing: 804300, facility_sub_type: "Golf Course" },
  { site_name: "Mcdonald Golf Club", town: "ELLON", easting: 395100, northing: 831200, facility_sub_type: "Golf Course" },
  { site_name: "Meldrum House Hotel and Golf Club", town: "OLDMELDRUM", easting: 381199, northing: 829064, facility_sub_type: "Golf Course" },
  { site_name: "Myrus Golf Centre", town: "Macduff", easting: 370957, northing: 863726, facility_sub_type: "Golf Driving Range" },
  { site_name: "Newburgh-on-Ythan Golf Club", town: "NR ELLON", easting: 400200, northing: 825200, facility_sub_type: "Golf Course" },
  { site_name: "Newmachar Golf Club", town: "Aberdeen", easting: 388151, northing: 817022, facility_sub_type: "Golf Course" },
  { site_name: "Oldmeldrum Golf Club", town: "OLDMELDRUM", easting: 381400, northing: 827300, facility_sub_type: "Golf Course" },
  { site_name: "Peterhead Golf Club", town: "PETERHEAD", easting: 411900, northing: 847500, facility_sub_type: "Golf Course" },
  { site_name: "Pine Lodge Golf Centre", town: "Kemnay", easting: 374894, northing: 818151, facility_sub_type: "Golf Driving Range" },
  { site_name: "Portlethen Golf Club", town: "PORTLETHEN", easting: 392500, northing: 798300, facility_sub_type: "Golf Course" },
  { site_name: "Royal Tarlair Golf Club", town: "MACDUFF", easting: 371400, northing: 864600, facility_sub_type: "Golf Course" },
  { site_name: "Stonehaven Golf Club", town: "STONEHAVEN", easting: 388495, northing: 788670, facility_sub_type: "Golf Course" },
  { site_name: "Tarland Golf Club", town: "NR ABOYNE", easting: 348300, northing: 804600, facility_sub_type: "Golf Course" },
  { site_name: "Torphins Golf Club", town: "Banchory", easting: 361557, northing: 802701, facility_sub_type: "Golf Course" },
  { site_name: "Trump International Golf Links", town: "Aberdeen", easting: 398011, northing: 820343, facility_sub_type: "Golf Course" },
  { site_name: "Turriff Golf Club", town: "TURRIFF", easting: 371200, northing: 849800, facility_sub_type: "Golf Course" },
  { site_name: "Westhill Golf Club", town: "WESTHILL", easting: 382400, northing: 807800, facility_sub_type: "Golf Course" },
  { site_name: "Arbroath Artisan Golf Club", town: "NR ARBROATH", easting: 361600, northing: 739200, facility_sub_type: "Golf Course" },
  { site_name: "Brechin Golf and Squash Club", town: "BRECHIN", easting: 360300, northing: 762000, facility_sub_type: "Golf Course" },
  { site_name: "Carnoustie Golf Links", town: "CARNOUSTIE", easting: 355500, northing: 734100, facility_sub_type: "Golf Course" },
  { site_name: "Edzell Golf Club", town: "EDZELL", easting: 359900, northing: 768400, facility_sub_type: "Golf Course" },
  { site_name: "Forfar Golf Club", town: "FORFAR", easting: 347900, northing: 750600, facility_sub_type: "Golf Course" },
  { site_name: "Kirriemuir Golf Club", town: "KIRRIEMUIR", easting: 338800, northing: 755400, facility_sub_type: "Golf Course" },
  { site_name: "Letham Grange Hotel and Golf Courses", town: "NR ARBROATH", easting: 353000, northing: 748500, facility_sub_type: "Golf Course" },
  { site_name: "Monifieth Golf Courses", town: "MONIFIETH", easting: 350300, northing: 732600, facility_sub_type: "Golf Course" },
  { site_name: "Montrose Links Trust", town: "MONTROSE", easting: 372300, northing: 758200, facility_sub_type: "Golf Course" },
  { site_name: "Panmure Golf Club", town: "NR CARNOUSTIE", easting: 353700, northing: 733900, facility_sub_type: "Golf Course" },
  { site_name: "Piperdam Golf & Leisure Resort", town: "Dundee", easting: 330349, northing: 734702, facility_sub_type: "Golf Course" },
  { site_name: "Cardross Golf Club", town: "CARDROSS", easting: 234700, northing: 677400, facility_sub_type: "Golf Course" },
  { site_name: "Cowal Golf Club", town: "DUNOON", easting: 217900, northing: 678300, facility_sub_type: "Golf Course" },
  { site_name: "Helensburgh Golf Club", town: "Helensburgh", easting: 230700, northing: 683100, facility_sub_type: "Golf Course" },
  { site_name: "Machrihanish Golf Club", town: "Machrihanish", easting: 163920, northing: 620792, facility_sub_type: "Golf Course" },
  { site_name: "St Andrews Links Trust", town: "ST ANDREWS", easting: 350400, northing: 717100, facility_sub_type: "Golf Course" },
  { site_name: "Gleneagles Hotel", town: "AUCHTERARDER", easting: 291600, northing: 711400, facility_sub_type: "Golf Course" },
  { site_name: "Muirfield Golf Club", town: "Gullane", easting: 349081, northing: 683573, facility_sub_type: "Golf Course" },
  { site_name: "Royal Troon Golf Club", town: "TROON", easting: 232800, northing: 629700, facility_sub_type: "Golf Course" },
  { site_name: "Turnberry Hotel", town: "Girvan", easting: 220300, northing: 605900, facility_sub_type: "Golf Course" },
  { site_name: "West Lothian Golf Club", town: "LINLITHGOW", easting: 300400, northing: 679300, facility_sub_type: "Golf Course" },
  { site_name: "Uphall Golf Club", town: "UPHALL", easting: 305500, northing: 671300, facility_sub_type: "Golf Course" },
  { site_name: "Pumpherston Golf Course", town: "NR LIVINGSTON", easting: 307200, northing: 669200, facility_sub_type: "Golf Course" },
  { site_name: "Polkemmet Golf Course", town: "BATHGATE", easting: 292700, northing: 664800, facility_sub_type: "Golf Course" },
  { site_name: "Oatridge Golf Course", town: "Broxburn", easting: 304757, northing: 672911, facility_sub_type: "Golf Course" },
  { site_name: "Niddry Castle Golf Club", town: "WINCHBURGH", easting: 309400, northing: 674700, facility_sub_type: "Golf Course" },
  { site_name: "Linlithgow Golf Club", town: "LINLITHGOW", easting: 298800, northing: 675900, facility_sub_type: "Golf Course" },
  { site_name: "Kingsfield Golf Range", town: "Linlithgow", easting: 302697, northing: 677871, facility_sub_type: "Golf Course" },
  { site_name: "Harburn Golf Club", town: "West Calder", easting: 301981, northing: 663077, facility_sub_type: "Golf Course" },
  { site_name: "Greenburn Golf Club", town: "FAULDHOUSE", easting: 293400, northing: 660200, facility_sub_type: "Golf Course" },
  { site_name: "Deer Park Golf And Country Club", town: "Livingston", easting: 304200, northing: 669800, facility_sub_type: "Golf Course" },
  { site_name: "Bridgend and District Golf Club", town: "Linlithgow", easting: 303967, northing: 675616, facility_sub_type: "Golf Course" },
  { site_name: "Bathgate Golf Club", town: "BATHGATE", easting: 297500, northing: 668300, facility_sub_type: "Golf Course" },
  { site_name: "Crail Golfing Society", town: "CRAIL", easting: 363400, northing: 709800, facility_sub_type: "Golf Course" },
  { site_name: "Cupar Golf Club", town: "CUPAR", easting: 337700, northing: 713500, facility_sub_type: "Golf Course" },
  { site_name: "Duke's Golf Course", town: "St Andrews", easting: 347825, northing: 714479, facility_sub_type: "Golf Course" },
  { site_name: "Dunfermline Golf Club", town: "DUNFERMLINE", easting: 306300, northing: 686300, facility_sub_type: "Golf Course" },
  { site_name: "Dunnikier Park Golf Course", town: "KIRKCALDY", easting: 327900, northing: 694300, facility_sub_type: "Golf Course" },
  { site_name: "Elie Golf House Club", town: "Leven", easting: 348590, northing: 700122, facility_sub_type: "Golf Course" },
  { site_name: "Falkland Golf Club", town: "FALKLAND", easting: 325600, northing: 707500, facility_sub_type: "Golf Course" },
  { site_name: "Kinghorn Golf Course", town: "KINGHORN", easting: 326600, northing: 686500, facility_sub_type: "Golf Course" },
  { site_name: "Kingsbarns Golf Links", town: "ST ANDREWS", easting: 360107, northing: 711989, facility_sub_type: "Golf Course" },
  { site_name: "Ladybank Golf Club", town: "LADYBANK", easting: 330400, northing: 710500, facility_sub_type: "Golf Course" },
  { site_name: "Leslie Golf Club", town: "GLENROTHES", easting: 324800, northing: 702100, facility_sub_type: "Golf Course" },
  { site_name: "Leven Links", town: "LEVEN", easting: 338600, northing: 701300, facility_sub_type: "Golf Course" },
  { site_name: "Lochgelly Golf Club", town: "LOCHGELLY", easting: 318100, northing: 693500, facility_sub_type: "Golf Course" },
  { site_name: "Lundin Golf Club", town: "LUNDIN LINKS", easting: 340900, northing: 702500, facility_sub_type: "Golf Course" },
  { site_name: "Pitreavie (Dunfermline) Golf Club", town: "DUNFERMLINE", easting: 310500, northing: 685600, facility_sub_type: "Golf Course" },
  { site_name: "Scotscraig Golf Club", town: "TAYPORT", easting: 346100, northing: 728000, facility_sub_type: "Golf Course" },
  { site_name: "Baberton Golf Club", town: "NR EDINBURGH", easting: 319700, northing: 668900, facility_sub_type: "Golf Course" },
  { site_name: "Bruntsfield Links Golfing Society", town: "EDINBURGH", easting: 319900, northing: 675700, facility_sub_type: "Golf Course" },
  { site_name: "Duddingston Golf Club", town: "EDINBURGH", easting: 329100, northing: 672100, facility_sub_type: "Golf Course" },
  { site_name: "Marriott Dalmahoy Hotel And Country Club", town: "Nr Edinburgh", easting: 314400, northing: 668700, facility_sub_type: "Golf Course" },
  { site_name: "Mortonhall Golf Club", town: "EDINBURGH", easting: 324400, northing: 669300, facility_sub_type: "Golf Course" },
  { site_name: "Murrayfield Golf Club", town: "EDINBURGH", easting: 321900, northing: 673700, facility_sub_type: "Golf Course" },
  { site_name: "Prestonfield Golf Club", town: "EDINBURGH", easting: 327200, northing: 672100, facility_sub_type: "Golf Course" },
  { site_name: "Ratho Park Golf Club", town: "RATHO", easting: 315000, northing: 670800, facility_sub_type: "Golf Course" },
  { site_name: "Royal Burgess Golfing Society of Edinburgh", town: "EDINBURGH", easting: 318500, northing: 675100, facility_sub_type: "Golf Course" },
  { site_name: "Swanston Golf Club", town: "EDINBURGH", easting: 323900, northing: 667400, facility_sub_type: "Golf Course" },
  { site_name: "Turnhouse Golf Club", town: "EDINBURGH", easting: 316700, northing: 673800, facility_sub_type: "Golf Course" }
];
